name: Trigger deployment for Program Reboot

on:
  workflow_dispatch:
    inputs:
      program_member:
        type: boolean
        default: false
        description: Deploy program member

permissions:
  id-token: write
  contents: read

jobs:
  deploy-program-member:
    if: ${{ inputs.program_member == 'true' }}
#    uses: 'icariohealth/dhp-program-member/.github/workflows/reboot.yaml@feat/reboot'
    uses: 'icariohealth/.github/.github/workflows/deploy-argo-application.yml@v1.0.6'
    secrets: inherit